version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY}/${BACKEND_IMAGE}:latest
    container_name: backend-app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - dev-community-network

  frontend:
    image: ${DOCKER_REGISTRY}/${FRONTEND_IMAGE:-nginx:alpine}
    container_name: react-app
    ports:
      - "${FRONTEND_PROD_PORT:-9999}:80"
    depends_on:
      - backend
    networks:
      - dev-community-network

networks:
  dev-community-network:
    driver: bridge
