version: '3.8'

services:
  frontend:
    image: ${DOCKER_REGISTRY}/${FRONTEND_IMAGE}:latest
    ports:
      - "${FRONTEND_PROD_PORT:-80}:80"
    volumes:
      - ./frontend-nginx-logs:/var/log/nginx
    networks:
      - dev-network
  cypress:
    image: cypress/included:12.0.0
    working_dir: /e2e
    volumes:
      - ./dev-community/dev-community-frontend/:/e2e
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:80
    command: ["npx", "cypress", "run", "--config-file", "/e2e/cypress.config.js", "--config", "baseUrl=http://frontend:80"]
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
