version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_community
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-network

  backend:
    build:
      context: ./dev-community-backend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/${BACKEND_IMAGE}:latest
    container_name: backend-app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dev_community?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    volumes:
      - ./backend-logs:/app/logs
    depends_on:
      - db
    networks:
      - dev-network

  frontend:
    build:
      context: ./dev-community-frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://backend:${BACKEND_PORT}
    image: ${DOCKER_REGISTRY}/${FRONTEND_IMAGE}:latest
    container_name: react-app
    ports:
      - "${FRONTEND_PROD_PORT:-80}:80"
    volumes:
      - ./frontend-nginx-logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql-data:
