version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_community
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-network

  backend:
    image: ${DOCKER_REGISTRY}/${BACKEND_IMAGE}:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      # 아래 키만 선언. 실제 값은 SSH에서 export된 환경 변수를 읽어감.
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
    volumes:
      - ./backend-logs:/app/logs
    depends_on:
      - db
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql-data:
