version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
    ports:
      -8081:8081
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:8081
    depends_on:
      - backend

  cypress:
    image: cypress/included:12.0.0
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    depends_on:
      - frontend
    command: ["npx", "cypress", "run", "--config", "baseUrl=http://frontend"]
