version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_community
    networks:
      - test-network

  backend:
    build:
      context: ./dev-community-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dev_community?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      MAIL_HOST: mail.sogang.ac.kr
      MAIL_PORT: 465
      MAIL_USERNAME: jesjsjes@sogang.ac.kr
      MAIL_PASSWORD: wndrnrwlq1492@
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - test-network

  frontend:
    build:
      context: ./dev-community-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8081
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - test-network

  cypress:
    image: cypress/included:12.0.0
    working_dir: /e2e
    volumes:
      - ./dev-community-frontend:/e2e
    depends_on:
      - frontend
    command: ["npx", "cypress", "run", "--config", "baseUrl=http://frontend"]
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
