# dev-community/prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8002']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['${BACKEND_URL}:8001']

  - job_name: 'cadvisor'
    # cAdvisor 컨테이너는 동일한 Docker 네트워크 안에 있으므로 서비스 이름과 컨테이너 내부 포트를 사용합니다.
    # 호스트 포트 변경과 무관하게 컨테이너 내부 포트 8080을 그대로 사용합니다.
    static_configs:
      - targets: ['cadvisor:8082'] 

  - job_name: 'backend_app'
    static_configs:
      - targets: ['backend:8081']
    metrics_path: '/actuator/prometheus'
